const style = {
  mediaCard: {
    "& h1": {
      fontSize: "30px",
    },
    "& h2": {
      fontSize: "15px",
      marginTop: "20px",
      color: "#5f5f5f",
    },
    "& img": {
      width: "100%",
      height: "200px",
      objectFit: "cover",
    },
    "& p": {
      fontSize: "14px",
      marginTop: "10px",
      color: "#5f5f5f",
      letterSpacing: "0.2px",
      "& a": {
        textDecoration: "none",
        color: "#a6a6a6",
      },
    },
  },
  cardBox: {
    boxShadow: "0 1px 3px rgba(32,33,36,.28)",
    padding: "15px",
    height: "100%",
    background: "#fff",
  },
  blogTagcss: {
    borderRadius: "5px",
    width: "10%",
    height: "5%",
    margin: "2px 5px 2px",
    "& h1": {
      fontSize: "14px !important",
      textAlign: "center",
      padding: "5px",
    },
  },
  chip: {
    borderRadius: "5px",
    width: "fit-content",
    padding: "2px 16px",
    color: "#fff",
    marginBottom: "10px",
    height: "26px",
    fontSize: "14px",
  },
  userdetails: {
    margin: "10px 0",
    display: "flex",
    gap: "10px",
  },
  howit__workSection: {
    position: "relative",
    marginTop: "60px",
    "& h2": {
      fontFamily: "Inter",
      fontSize: "50px",
      color: "#0C091B",
      width: "100%",
      textAlign: "center",
      textTransform: "uppercase",
    },
  },
  headSection: {
    position: "relative",
    overflow: "hidden",
    "& img": {
      borderRadius: "0 0 50% 50%/0 0 30% 30%",
      transform: "scaleX(1.1)",
      height: "500px",
      objectFit: "fill",
    },
    "&:after": {
      position: "absolute",
      zIndex: "1",
      top: "0",
      left: "0",
      width: "100%",
      height: "100%",
      content: "''",
      opacity: ".5",
      background: "#000",
      borderRadius: "0 0 50% 50%/0 0 30% 30%",
      transform: "scaleX(1.1)",
    },
  },
  ourNewRoom: {
    position: "absolute",
    top: "50%",
    width: "600px",
    zIndex: "3",
    transform: "translate(-50%, -50%)",
    left: "50%",
    "& h6": {
      color: "#fff",
      fontSize: "30px",
      textAlign: "center",
      marginBottom: "25px",
    },
  },
  inputSection: {
    position: "relative",
    "& input": {
      width: "100%",
      borderRadius: "5px",
      height: "40px",
      padding: "10px 30px",
      color: "#c3c3c3",
      border: "0",
      fontSize: "14px",
      position: "relative",
    },
    "& button": {
      position: "absolute",
      top: "50%",
      right: "5px",
      background: "#1565d8",
      padding: "4px",
      width: "75px",
      fontSize: "12px",
      color: "#fff",
      transform: "translateY(-50%)",
      "&:hover": {
        background: "#034db7",
      },
    },
  },
  SearchIcon: {
    position: "absolute",
    top: "50%",
    left: "5px",

    color: "#c5c1c1",
    transform: "translateY(-50%)",
    "& svg": {
      fontSize: "22px",
    },
  },
  popularTag: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginTop: "20px",
    "& p": {
      color: "#fff",
      fontSize: "14px",
    },
    "& button": {
      backgroundColor: "transparent",
      border: "1px solid #fff",
      padding: "5px 15px",
      color: "#fff",
      fontSize: "12px",
    },
  },

  dFlex: {
    display: "flex",
  },
  topSectionDetails: {
    padding: "30px",
    display: "flex",
    height: "100%",
    flexDirection: "column",
    justifyContent: "center",
    "& h1": {
      fontSize: "35px",
      color: "#183b56",
      margin: "15px 0",
    },
    "& p": {
      color: "#798b9b",
      fontSize: "14px",
      letterSpacing: "0.2px",
    },
    "& button": {
      color: "#63c49b",
      padding: "6px 15px",
      borderRadius: "100px",
      fontSize: "12px",
      backgroundColor: "#ebf7f2",
      width: "113px",
    },
  },
  cardBottomSection: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: "23px",
  },
  profileDetails: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  profileName: {
    "& span": {
      backgroundColor: "#ebf7f2",
      width: "16px",
      height: "16px",
      borderRadius: "100px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      marginRight: "10px",
      "& svg": {
        fontSize: "12px",
        color: "#36b37e",
      },
    },
    "& h5": {
      fontSize: "14px",
    },
  },
  date: {
    fontSize: "14px",
  },

  popularArticles: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "30px",
    marginTop: "30px",
    "& h2": {
      fontSize: "40px",
      color: "#183b56",
    },
    "& p": {
      color: "#798b9b",
      fontSize: "14px",
      letterSpacing: "0.2px",
      marginTop: "10px",
    },
    "& button": {
      color: "#1565d8",
      padding: "6px 15px",
      borderRadius: "5px",
      fontSize: "12px",
      backgroundColor: "transparent",
      border: "2px solid #1565d8",
      "& svg": {
        fontSize: "14px",
        marginLeft: "5px",
      },
    },
  },
  popularArticlesDetails: {
    width: "50%",
  },
  popularArticlesList: {
    position: "relative",
    borderRadius: "15px",
    overflow: "hidden",
    "&:after": {
      content: "''",
      width: "100%",
      height: "100%",
      position: "absolute",
      left: "0",
      bottom: "0",
      zIndex: "0",
      webkitTransition: "all 0.35s ease-in-out",
      transition: "all 0.35s ease-in-out",
      opacity: "1",
      background: "#364652",
      background: "linear-gradient(rgb(255 255 255 / 0%) 0%, #152532 71.87%)",
    },
  },
  popularArticlesHeading: {
    position: "absolute",
    bottom: "20px",
    left: "50%",
    right: "auto",
    transform: "translateX(-50%)",
    width: "100%",
    margin: "auto",
    zIndex: "2",
    paddingLeft: "2rem",
    paddingRight: "2rem",
    "& h3": {
      fontSize: "30px",
      color: "#fff",
    },
    "& h4": {
      fontSize: "25px",
      color: "#fff",
      marginBottom: "10px",
    },
    "& p": {
      color: "#fff",
      fontSize: "14px",
      letterSpacing: "0.2px",
      display: "-webkit-box",
      "-webkit-line-clamp": "2",
      "-webkit-box-orient": "vertical",
      overflow: "hidden",
      textOverflow: "ellipsis",
    },
  },

  caseStudySlider: {
    "& .slick-prev": {
      zIndex: "999",
      "&::before": {
        fontSize: "35px",
        zIndex: "99",
        opacity: "1",
        content: "''",
        width: "50px",
        height: "45px",
        background:
          "url(/images/home/left.svg) center center / contain no-repeat",
        position: "absolute",
        left: "0",
        top: "0",
      },
    },
    "& .slick-next": {
      zIndex: "999",
      "&::before": {
        fontSize: "35px",
        zIndex: "99",
        opacity: "1",
        content: "''",
        width: "50px",
        height: "45px",
        background:
          "url(/images/home/right.svg) center center / contain no-repeat",
        position: "absolute",
        right: "0",
        top: "0",
      },
    },
  },
  showListInput: {
    overflowY: "auto",
    height: "300px",
    position: "absolute",
    width: "100%",
    top: "100%",
    zIndex: "9",
    color: "#000",
    "& p": {
      textAlign: "center",
    },
    "& ul": {
      padding: "0",
      margin: "0",
      background: "#fff",

      "& li": {
        color: "#000",
        fontSize: "14px",
        fontWeight: "300",
        padding: "9px 15px",
        borderBottom: "1px solid #c3c3c3",
      },
    },
  },
};

export default style;
