const PORT = process.env.NEXT_PUBLIC_PORT;

const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
const GEOLOCATION_URL = process.env.NEXT_PUBLIC_GEOLOCATION_URL;

export {
  PORT,
  GEOLOCATION_URL,
  API_BASE_URL,
};
