const PORT = process.env.NEXT_PUBLIC_PORT;

const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
const GEOLOCATION_URL = process.env.NEXT_PUBLIC_GEOLOCATION_URL;
const API_GENERATIVE_LANGUAGE_CLIENT = process.env.NEXT_PUBLIC_API_GENERATIVE_LANGUAGE_CLIENT;

export { PORT, GEOLOCATION_URL, API_BASE_URL, API_GENERATIVE_LANGUAGE_CLIENT };
