const AWS_ACCESS_KEY = process.env.NEXT_PUBLIC_AWS_ACCESS_KEY;
const AWS_SECRET_ACCESS_KEY = process.env.NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY;
const GOOGLE_CLOUD_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLOUD_CLIENT_ID;
const GOOGLE_CLOUD_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_GOOGLE_CLOUD_CLIENT_SECRET;

const MONGODB_URL = process.env.NEXT_PUBLIC_MONGODB_URL;
const PORT = process.env.NEXT_PUBLIC_PORT;
const JWT_SECRET = process.env.NEXT_PUBLIC_JWT_SECRET;
const JWT_ACCESS_EXPIRATION_MINUTES =
  process.env.NEXT_PUBLIC_JWT_ACCESS_EXPIRATION_MINUTES;
const JWT_REFRESH_EXPIRATION_DAYS =
  process.env.NEXT_PUBLIC_JWT_REFRESH_EXPIRATION_DAYS;

const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
const GEOLOCATION_URL = process.env.NEXT_PUBLIC_GEOLOCATION_URL;

export {
  AWS_ACCESS_KEY,
  AWS_SECRET_ACCESS_KEY,
  GOOGLE_CLOUD_CLIENT_ID,
  GOOGLE_CLOUD_CLIENT_SECRET,
  MONGODB_URL,
  PORT,
  GEOLOCATION_URL,
  JWT_SECRET,
  JWT_ACCESS_EXPIRATION_MINUTES,
  JWT_REFRESH_EXPIRATION_DAYS,
  API_BASE_URL,
};
